### ISSUE TITLE
02_01b

### ISSUE THREAD

**Issue by nickmortensen** [planetoftheweb/postcsslayouts#5]
Had an initial issue with erroring out when trying to save my postcss -- turned out that it didn't like the google font.

I am using node v8.1.2 and npm v5.0.3, I don't know if something has changed in this node version to create the error in trying to import the google font or it was a unique error to my experience, but you may find it valuable to pass along. 

Solved it by adding this to the node modules:
 [postcss-google-font](https://github.com/yordis/postcss-google-font)

alternatively, from the NPM site [postcss-google-font](https://www.npmjs.com/package/postcss-google-font/tutorial)

(add using npm in terminal) `npm i postcss-google-font`

I then altered the gulpfile.js slightly to (appended lines are below comments)

```
var gulp = require('gulp'),
  gutil = require('gulp-util'),
  webserver = require('gulp-webserver'),
  postcss = require('gulp-postcss'),
  autoprefixer = require('autoprefixer'),
  precss = require('precss'),
  cssnano = require('cssnano'),
  animation = require('postcss-animation'),
  //added in the following to utilize postcss-google-fonts
  googlefonts = require('postcss-google-font'),

  source = 'process/css/',
  dest = 'builds/postcss/';

gulp.task('html', function() {
  gulp.src(dest + '*.html');
});

gulp.task('css', function() {
  gulp.src(source + 'style.css')
  .pipe(postcss([
    //added in the following to utilize postcss-google-fonts
    googlefonts(),
    precss(),
    animation(),
    autoprefixer(),
    cssnano()
  ]))
  .on('error', gutil.log)
  .pipe(gulp.dest(dest + 'css'));
});

gulp.task('watch', function() {
  gulp.watch(source + '**/*.css', ['css']);
  gulp.watch(dest + '**/*.html', ['html']);
});

gulp.task('webserver', function() {
  gulp.src(dest)
    .pipe(webserver({
      livereload: true,
      open: true
    }));
});

gulp.task('default', ['html', 'css', 'webserver','watch']);


```

Seemed to solve the error.  FYI.  

Dig your tutorials, I've learned a ton from you.

**Comment by planetoftheweb** [comment]
Thanks for the note. It's weird that you'd have to ask a node module to just use a google font.  Glad you figured it out...although it seems like more of a bug. I'll keep an eye out for it.
